// AUTO-GENERATED by scripts/brand_sync.py from config/brand.json. Do not edit.

export const BRAND = {
  api_key_prefix: "or",
  brand_slug: "omnirank",
  colors: {
    primary: "#2563eb",
    primary_foreground: "#ffffff",
  },
  company_name: "OmniRank",
  crawler_user_agent_token: "OmniRankBot",
  dns_txt_prefix: "omnirank-verification=",
  email_from_name: "OmniRank",
  npm_scope: "@omnirank",
  product_name: "OmniRank",
  public_api_url: "https://api.omnirank.com",
  sdk_package: "@omnirank/sdk",
  site_key_prefix: "ors",
  snippet_filename: "agent.js",
  snippet_global: "OmniRank",
  verification_meta_name: "omnirank-verification",
  wp_plugin_slug: "omnirank",
} as const;

export type Brand = typeof BRAND;
