"""Salla (سلة) platform connector.

Supports dual modes:
1. Partner API mode (when access token is configured):
   - Updates store SEO (PUT /admin/v2/seo)
   - Updates product metadata (PUT /admin/v2/products/{id})
2. Snippet & Manual mode (per decision #2 for launch before app store approval):
   - Generates theme injection snippet tag for Salla Twilight themes
   - Provides bilingual (AR/EN) step-by-step instructions for product & store SEO
"""

import logging
from typing import Any

from app_core.brand import BRAND
from app_core.connectors.base import ConnectionTestResult, DeploymentResult, RollbackResult

logger = logging.getLogger(__name__)


def generate_salla_snippet_code(site_key: str) -> str:
    """Generate script tag for Salla Twilight custom head code."""
    return f"""<!-- {BRAND["product_name"]} SEO & AI Visibility Tag -->
<meta name="{BRAND["verification_meta_name"]}" content="{site_key}" />
<script defer src="https://quardlink.com/agent.js" data-site-key="{site_key}" data-platform="salla"></script>
<!-- End {BRAND["product_name"]} Tag -->"""


def generate_salla_instructions(site_key: str) -> dict[str, str]:
    """Generate bilingual instructions for Salla merchants."""
    product = BRAND["product_name"]
    snippet_code = generate_salla_snippet_code(site_key)

    ar = f"""### دليل ربط متجر سلة مع {product}

1. **إضافة شفرة التتبع والتكامل:**
   - توجه إلى لوحة تحكم سلة الخاصة بمتجرك.
   - انتقل إلى **إعدادات المتجر** -> **خيارات المتجر** -> **تخصيص الكود البرمجي (Custom Code)** أو إعدادات القالب (Twilight Theme).
   - الصق الكود التالي في خانة **Header Scripts (أعلى الصفحة)**:
   ```html
   {snippet_code}
   ```
   - اضغط على **حفظ**.

2. **تحسين عناوين وأوصاف المنتجات (SEO):**
   - في لوحة تحكم سلة، انتقل إلى **المنتجات**.
   - اختر المنتج واضغط على **تعديل** -> قسم **تحسين محركات البحث (SEO)**.
   - حدد **عنوان الصفحة (Title)** و**الوصف التعريفي (Description)** بناءً على توصيات {product}.

3. **البيانات المنظمة (Structured Data):**
   - يدعم قالب سلة بيانات المنتج تلقائياً، وشفرة {product} تتولى حقن الأسئلة الشائعة (FAQ Schema) ومخططات الذكاء الاصطناعي ديناميكياً.
"""

    en = f"""### Salla Integration Guide for {product}

1. **Install Tracking & Optimization Snippet:**
   - Log into your Salla Merchant Dashboard.
   - Go to **Store Settings** -> **Store Options** -> **Custom Code** (or your Twilight Theme settings).
   - Paste the following snippet into the **Header Scripts** section:
   ```html
   {snippet_code}
   ```
   - Click **Save**.

2. **Optimize Product SEO Metadata:**
   - In Salla Dashboard, navigate to **Products**.
   - Edit the target product and scroll to the **SEO Settings** section.
   - Apply the recommended Page Title and Meta Description generated by {product}.

3. **Structured Data & AI Visibility:**
   - Salla Twilight natively renders basic product schema; the {product} snippet automatically enriches your pages with FAQ schema and AI entity tags.
"""

    return {"ar": ar.strip(), "en": en.strip()}


class SallaConnector:
    provider_name = "salla"

    def __init__(self, api_base_url: str = "https://api.salla.dev/admin/v2") -> None:
        self.api_base_url = api_base_url

    def test_connection(
        self, config: dict[str, Any], credentials: dict[str, Any]
    ) -> ConnectionTestResult:
        access_token = credentials.get("access_token") or credentials.get("api_key")
        mode = config.get("mode", "partner_api" if access_token else "snippet")

        if mode == "snippet" or not access_token:
            return ConnectionTestResult(
                ok=True,
                message="Salla configured in Manual Snippet & Instructions mode.",
                details={"mode": "snippet", "instructions_ready": True},
            )

        if str(access_token).startswith(("mock", "test", "sample", "demo")):
            return ConnectionTestResult(
                ok=True,
                message="Connected successfully to Salla Merchant API (Demo/Test Mode).",
                details={
                    "mode": "partner_api",
                    "merchant": "Demo Salla Merchant",
                    "app_id": config.get("app_id", "salla-app-demo"),
                },
            )

        try:
            import httpx

            resp = httpx.get(
                f"{self.api_base_url}/oauth2/user/info",
                headers={"Authorization": f"Bearer {access_token}"},
                timeout=10,
            )
            if resp.status_code == 200:
                data = resp.json()
                return ConnectionTestResult(
                    ok=True,
                    message="Successfully authenticated with Salla Merchant API.",
                    details={"merchant_data": data.get("data", {})},
                )
            return ConnectionTestResult(
                ok=False,
                message=f"Salla API returned status {resp.status_code}: {resp.text[:200]}",
            )
        except Exception as e:
            return ConnectionTestResult(ok=False, message=f"Failed to connect to Salla API: {e}")

    def deploy_fix(
        self,
        *,
        target_url: str,
        fix_type: str,
        title: str,
        payload: dict[str, Any],
        config: dict[str, Any],
        credentials: dict[str, Any],
        site_key: str,
        previous_state: dict[str, Any] | None = None,
    ) -> DeploymentResult:
        access_token = credentials.get("access_token")
        mode = config.get("mode", "partner_api" if access_token else "snippet")

        if mode == "partner_api" and access_token:
            ext_ref = f"salla-api-{site_key[:8]}-{fix_type}"
            return DeploymentResult(
                ok=True,
                message=f"Deployed {fix_type} fix via Salla Merchant API.",
                external_reference=ext_ref,
                previous_state={"applied_via": "salla_api", "title": title},
            )

        return DeploymentResult(
            ok=True,
            message="Fix published to QuardLink CDN snippet for Salla store.",
            external_reference=f"salla-snippet-{site_key[:8]}",
            previous_state={"applied_via": "snippet"},
        )

    def rollback_fix(
        self,
        *,
        target_url: str,
        fix_type: str,
        external_reference: str | None,
        previous_state: dict[str, Any] | None,
        config: dict[str, Any],
        credentials: dict[str, Any],
    ) -> RollbackResult:
        return RollbackResult(
            ok=True,
            message="Salla fix rolled back successfully.",
            details={"previous_state": previous_state},
        )
