#!/usr/bin/env python3
"""Generate brand constants for every app from config/brand.json.

Usage:
    python scripts/brand_sync.py          # write generated files
    python scripts/brand_sync.py --check  # exit 1 if any generated file is stale (CI)

Add a new target by appending to TARGETS. Generated files must never be edited by hand.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND_FILE = ROOT / "config" / "brand.json"
HEADER = "AUTO-GENERATED by scripts/brand_sync.py from config/brand.json. Do not edit."


def load_brand() -> dict:
    data = json.loads(BRAND_FILE.read_text(encoding="utf-8"))
    return {k: v for k, v in data.items() if not k.startswith("_")}


def render_python(brand: dict) -> str:
    items = []
    for k in sorted(brand.keys()):
        v = brand[k]
        if isinstance(v, dict):
            inner = ", ".join(
                f'"{ik}": {json.dumps(iv, ensure_ascii=False)}' for ik, iv in sorted(v.items())
            )
            items.append(f'    "{k}": {{{inner}}},')
        else:
            items.append(f'    "{k}": {json.dumps(v, ensure_ascii=False)},')
    body = "\n".join(items)
    return f'"""{HEADER}"""\n\nfrom typing import Any\n\nBRAND: dict[str, Any] = {{\n{body}\n}}\n'


def render_typescript(brand: dict) -> str:
    items = []
    for k in sorted(brand.keys()):
        v = brand[k]
        if isinstance(v, dict):
            inner_lines = [
                f"    {ik}: {json.dumps(iv, ensure_ascii=False)}," for ik, iv in sorted(v.items())
            ]
            inner = "\n".join(inner_lines)
            items.append(f"  {k}: {{\n{inner}\n  }},")
        else:
            items.append(f"  {k}: {json.dumps(v, ensure_ascii=False)},")
    body = "\n".join(items)
    return f"// {HEADER}\n\nexport const BRAND = {{\n{body}\n}} as const;\n\nexport type Brand = typeof BRAND;\n"


TARGETS: list[tuple[str, Callable[[dict], str]]] = [
    ("packages/core/app_core/brand_gen.py", render_python),
    ("apps/web/src/lib/brand.gen.ts", render_typescript),
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    brand = load_brand()
    stale: list[str] = []
    for rel, render in TARGETS:
        path = ROOT / rel
        content = render(brand)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {rel}")

    if stale:
        print("Stale brand files (run `python scripts/brand_sync.py`):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
