"""foundation: users, orgs, memberships, plans, sites, keywords, prompts, audit log + RLS

Revision ID: 0001
Revises:
Create Date: 2026-09-29 17:29:58.693904
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tables whose rows belong to one org. Every table with an org_id column must be listed
# here or in a later migration (enforced by tests/test_rls.py).
TENANT_TABLES = ("memberships", "invitations", "subscriptions", "sites", "keywords", "ai_prompts")

RLS_UP = [
    """DO $$ BEGIN
         IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_tenant') THEN
           CREATE ROLE app_tenant NOLOGIN;
         END IF;
       END $$""",
    "GRANT app_tenant TO CURRENT_USER",
    "GRANT USAGE ON SCHEMA public TO app_tenant",
    """CREATE FUNCTION app_current_org() RETURNS uuid LANGUAGE sql STABLE AS
       $$ SELECT NULLIF(current_setting('app.org_id', true), '')::uuid $$""",
    """CREATE FUNCTION app_current_user() RETURNS uuid LANGUAGE sql STABLE AS
       $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$""",
    *[
        stmt
        for t in TENANT_TABLES
        for stmt in (
            f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY",
            f"CREATE POLICY tenant_isolation ON {t} USING (org_id = app_current_org())"
            f" WITH CHECK (org_id = app_current_org())",
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO app_tenant",
        )
    ],
    # organizations: a tenant sees and edits only its own org, never creates or deletes one.
    "ALTER TABLE organizations ENABLE ROW LEVEL SECURITY",
    "CREATE POLICY tenant_isolation ON organizations USING (id = app_current_org())",
    "GRANT SELECT, UPDATE ON organizations TO app_tenant",
    # users: visible only if they belong to the current org (or are the current user).
    "ALTER TABLE users ENABLE ROW LEVEL SECURITY",
    """CREATE POLICY tenant_visibility ON users FOR SELECT USING (
         id = app_current_user()
         OR EXISTS (SELECT 1 FROM memberships m
                    WHERE m.user_id = users.id AND m.org_id = app_current_org()))""",
    "GRANT SELECT ON users TO app_tenant",
    # audit_log: append + read own org's entries.
    "ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY",
    "CREATE POLICY tenant_isolation ON audit_log USING (org_id = app_current_org())"
    " WITH CHECK (org_id = app_current_org())",
    "GRANT SELECT, INSERT ON audit_log TO app_tenant",
    "GRANT USAGE ON SEQUENCE audit_log_id_seq TO app_tenant",
    # plans: global, read-only for tenants. refresh_tokens: no tenant access at all.
    "GRANT SELECT ON plans TO app_tenant",
]

RLS_DOWN = [
    *[
        f"DROP POLICY IF EXISTS tenant_isolation ON {t}"
        for t in (*TENANT_TABLES, "organizations", "audit_log")
    ],
    "DROP POLICY IF EXISTS tenant_visibility ON users",
    "DROP FUNCTION IF EXISTS app_current_org()",
    "DROP FUNCTION IF EXISTS app_current_user()",
    "REVOKE ALL ON ALL TABLES IN SCHEMA public FROM app_tenant",
    "REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM app_tenant",
    "REVOKE USAGE ON SCHEMA public FROM app_tenant",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("max_sites", sa.Integer(), nullable=False),
        sa.Column("max_keywords", sa.Integer(), nullable=False),
        sa.Column("max_prompts", sa.Integer(), nullable=False),
        sa.Column("max_engines", sa.Integer(), nullable=False),
        sa.Column("allowed_engines", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("max_languages_per_site", sa.Integer(), nullable=False),
        sa.Column("addon_languages", postgresql.ARRAY(sa.String(length=10)), nullable=False),
        sa.Column("check_frequency", sa.String(length=20), nullable=False),
        sa.Column("audits_per_month", sa.Integer(), nullable=False),
        sa.Column("monthly_cost_ceiling_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("trial_days", sa.Integer(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("ui_language", sa.String(length=10), server_default="en", nullable=False),
        sa.Column("google_sub", sa.String(length=255), nullable=True),
        sa.Column("is_platform_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("plan_assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("plan_assigned_by", sa.UUID(), nullable=True),
        sa.Column(
            "addons", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("cost_ceiling_override_usd", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_assigned_by"],
            ["users.id"],
            name=op.f("fk_organizations_plan_assigned_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_organizations_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=True),
        sa.Column("target_id", sa.String(length=80), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_audit_log_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('admin', 'member', 'viewer')", name=op.f("ck_invitations_role")
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(op.f("ix_invitations_org_id"), "invitations", ["org_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer')", name=op.f("ck_memberships_role")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("org_id", "user_id", name="uq_memberships_org_user"),
    )
    op.create_index(op.f("ix_memberships_org_id"), "memberships", ["org_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "sites",
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("homepage_url", sa.Text(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("platform_confirmed", sa.Boolean(), nullable=False),
        sa.Column("rendering", sa.String(length=20), nullable=False),
        sa.Column("primary_language", sa.String(length=10), server_default="en", nullable=False),
        sa.Column(
            "additional_languages",
            postgresql.ARRAY(sa.String(length=10)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("default_country", sa.String(length=2), nullable=False),
        sa.Column("default_city", sa.String(length=120), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column(
            "brand_names",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "competitor_domains",
            postgresql.ARRAY(sa.String(length=253)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("site_key", sa.String(length=64), nullable=False),
        sa.Column("verification_token", sa.String(length=64), nullable=False),
        sa.Column("verification_method", sa.String(length=30), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('wordpress', 'shopify', 'wix', 'webflow', 'squarespace', 'framer', 'salla', 'zid', 'nextjs', 'nuxt', 'react_spa', 'vue_spa', 'astro', 'static', 'custom_backend', 'unknown')",
            name=op.f("ck_sites_platform"),
        ),
        sa.CheckConstraint(
            "rendering IN ('server', 'client', 'hybrid', 'unknown')",
            name=op.f("ck_sites_rendering"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_sites_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_sites_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("org_id", "domain", name="uq_sites_org_domain"),
        sa.UniqueConstraint("site_key", name=op.f("uq_sites_site_key")),
    )
    op.create_index(op.f("ix_sites_org_id"), "sites", ["org_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("provider_subscription_id", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_subscriptions_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_subscriptions_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(op.f("ix_subscriptions_org_id"), "subscriptions", ["org_id"], unique=False)
    op.create_table(
        "ai_prompts",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("intent", sa.String(length=20), nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=50)), server_default="{}", nullable=False
        ),
        sa.Column("status", sa.String(length=10), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "intent IN ('informational', 'commercial', 'local', 'comparison', 'navigational')",
            name=op.f("ck_ai_prompts_intent"),
        ),
        sa.CheckConstraint("status IN ('active', 'paused')", name=op.f("ck_ai_prompts_status")),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_ai_prompts_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_ai_prompts_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_prompts")),
    )
    op.create_index(op.f("ix_ai_prompts_org_id"), "ai_prompts", ["org_id"], unique=False)
    op.create_index(op.f("ix_ai_prompts_site_id"), "ai_prompts", ["site_id"], unique=False)
    op.create_table(
        "keywords",
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("keyword", sa.String(length=300), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("device", sa.String(length=10), nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=50)), server_default="{}", nullable=False
        ),
        sa.Column("status", sa.String(length=10), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("device IN ('desktop', 'mobile')", name=op.f("ck_keywords_device")),
        sa.CheckConstraint("status IN ('active', 'paused')", name=op.f("ck_keywords_status")),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_keywords_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_keywords_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keywords")),
    )
    op.create_index(op.f("ix_keywords_org_id"), "keywords", ["org_id"], unique=False)
    op.create_index(op.f("ix_keywords_site_id"), "keywords", ["site_id"], unique=False)
    op.create_index(
        "uq_keywords_identity",
        "keywords",
        [
            "site_id",
            sa.literal_column("lower(keyword)"),
            "language",
            "country",
            sa.literal_column("coalesce(city, '')"),
            "device",
        ],
        unique=True,
    )
    # ### end Alembic commands ###

    # --- Row-level security (tenancy layer 2, see app_core/tenancy.py) -------------------
    for stmt in RLS_UP:
        op.execute(stmt)


def downgrade() -> None:
    for stmt in RLS_DOWN:
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_keywords_identity", table_name="keywords")
    op.drop_index(op.f("ix_keywords_site_id"), table_name="keywords")
    op.drop_index(op.f("ix_keywords_org_id"), table_name="keywords")
    op.drop_table("keywords")
    op.drop_index(op.f("ix_ai_prompts_site_id"), table_name="ai_prompts")
    op.drop_index(op.f("ix_ai_prompts_org_id"), table_name="ai_prompts")
    op.drop_table("ai_prompts")
    op.drop_index(op.f("ix_subscriptions_org_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_sites_org_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_org_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_invitations_org_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("organizations")
    op.drop_table("users")
    op.drop_table("plans")
    # ### end Alembic commands ###
