import type { components } from "./api-types.gen";

type S = components["schemas"];
export type SessionOut = S["SessionOut"];
export type UserOut = S["UserOut"];
export type OrgSummary = S["OrgSummary"];
export type OrgOut = S["OrgOut"];
export type PlanOut = S["PlanOut"];
export type MemberOut = S["MemberOut"];
export type InvitationOut = S["InvitationOut"];
export type SiteOut = S["SiteOut"];
export type SiteCreateIn = S["SiteCreateIn"];
export type SiteUpdateIn = S["SiteUpdateIn"];
export type KeywordIn = S["KeywordIn"];
export type KeywordOut = S["KeywordOut"];
export type PromptIn = S["PromptIn"];
export type PromptOut = S["PromptOut"];
export type AnalyzeOut = S["AnalyzeOut"];
export type SuggestOut = S["SuggestOut"];
export type CompleteIn = S["CompleteIn"];
export type AdminOrgOut = S["AdminOrgOut"];
export type Platform = SiteCreateIn["platform"];
