/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Healthz */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signup */
    post: operations["signup_auth_signup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Me */
    patch: operations["update_me_auth_me_patch"];
    trace?: never;
  };
  "/auth/verify-email/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Verification */
    post: operations["request_verification_auth_verify_email_request_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify Email */
    post: operations["verify_email_auth_verify_email_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Password Reset */
    post: operations["request_password_reset_auth_password_reset_request_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/password-reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset Password */
    post: operations["reset_password_auth_password_reset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/google/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google Start */
    get: operations["google_start_auth_google_start_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/google/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google Callback */
    get: operations["google_callback_auth_google_callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/orgs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List My Orgs */
    get: operations["list_my_orgs_orgs_get"];
    put?: never;
    /** Create Org */
    post: operations["create_org_orgs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/org": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Current Org */
    get: operations["get_current_org_org_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Current Org */
    patch: operations["update_current_org_org_patch"];
    trace?: never;
  };
  "/org/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Members */
    get: operations["list_members_org_members_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/org/members/{membership_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations["remove_member_org_members__membership_id__delete"];
    options?: never;
    head?: never;
    /** Update Member */
    patch: operations["update_member_org_members__membership_id__patch"];
    trace?: never;
  };
  "/org/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Invitations */
    get: operations["list_invitations_org_invitations_get"];
    put?: never;
    /** Create Invitation */
    post: operations["create_invitation_org_invitations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/org/invitations/{invitation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Invitation */
    delete: operations["revoke_invitation_org_invitations__invitation_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invitations/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept Invitation
     * @description Cross-org by nature (the user isn't a member yet), so it uses the system session.
     */
    post: operations["accept_invitation_invitations_accept_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sites */
    get: operations["list_sites_sites_get"];
    put?: never;
    /** Create Site */
    post: operations["create_site_sites_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sites/{site_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Site */
    get: operations["read_site_sites__site_id__get"];
    put?: never;
    post?: never;
    /** Delete Site */
    delete: operations["delete_site_sites__site_id__delete"];
    options?: never;
    head?: never;
    /** Update Site */
    patch: operations["update_site_sites__site_id__patch"];
    trace?: never;
  };
  "/sites/{site_id}/keywords": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Keywords */
    get: operations["list_keywords_sites__site_id__keywords_get"];
    put?: never;
    /** Add Keywords */
    post: operations["add_keywords_sites__site_id__keywords_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sites/{site_id}/keywords/{keyword_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Keyword */
    delete: operations["delete_keyword_sites__site_id__keywords__keyword_id__delete"];
    options?: never;
    head?: never;
    /** Set Keyword Status */
    patch: operations["set_keyword_status_sites__site_id__keywords__keyword_id__patch"];
    trace?: never;
  };
  "/sites/{site_id}/prompts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Prompts */
    get: operations["list_prompts_sites__site_id__prompts_get"];
    put?: never;
    /** Add Prompts */
    post: operations["add_prompts_sites__site_id__prompts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sites/{site_id}/prompts/{prompt_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Prompt */
    delete: operations["delete_prompt_sites__site_id__prompts__prompt_id__delete"];
    options?: never;
    head?: never;
    /** Set Prompt Status */
    patch: operations["set_prompt_status_sites__site_id__prompts__prompt_id__patch"];
    trace?: never;
  };
  "/onboarding/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Analyze */
    post: operations["analyze_onboarding_analyze_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/onboarding/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suggestions */
    post: operations["suggestions_onboarding_suggestions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/onboarding/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete
     * @description Create the site with its keywords and prompts in one transaction.
     */
    post: operations["complete_onboarding_complete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Public Plans */
    get: operations["list_public_plans_plans_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/orgs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Orgs */
    get: operations["list_orgs_admin_orgs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/orgs/{org_id}/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Org Plan */
    put: operations["set_org_plan_admin_orgs__org_id__plan_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/orgs/{org_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Org */
    patch: operations["update_org_admin_orgs__org_id__patch"];
    trace?: never;
  };
  "/admin/plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List All Plans */
    get: operations["list_all_plans_admin_plans_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/plans/{plan_code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Plan */
    patch: operations["update_plan_admin_plans__plan_code__patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminOrgOut */
    AdminOrgOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Plan Code */
      plan_code: string;
      /** Addons */
      addons: {
        [key: string]: unknown;
      };
      /** Cost Ceiling Override Usd */
      cost_ceiling_override_usd: string | null;
      /** Members */
      members: number;
      /** Sites */
      sites: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AdminOrgUpdateIn */
    AdminOrgUpdateIn: {
      /** Addons */
      addons?: {
        [key: string]: boolean;
      } | null;
      /** Cost Ceiling Override Usd */
      cost_ceiling_override_usd?: number | string | null;
    };
    /** AdminPlanUpdateIn */
    AdminPlanUpdateIn: {
      /** Name */
      name?: string | null;
      /** Is Public */
      is_public?: boolean | null;
      /** Max Sites */
      max_sites?: number | null;
      /** Max Keywords */
      max_keywords?: number | null;
      /** Max Prompts */
      max_prompts?: number | null;
      /** Max Engines */
      max_engines?: number | null;
      /** Allowed Engines */
      allowed_engines?: string[] | null;
      /** Max Languages Per Site */
      max_languages_per_site?: number | null;
      /** Addon Languages */
      addon_languages?: string[] | null;
      /** Check Frequency */
      check_frequency?: ("weekly" | "twice_weekly" | "daily") | null;
      /** Audits Per Month */
      audits_per_month?: number | null;
      /** Monthly Cost Ceiling Usd */
      monthly_cost_ceiling_usd?: number | string | null;
      /** Trial Days */
      trial_days?: number | null;
    };
    /** AdminSetPlanIn */
    AdminSetPlanIn: {
      /** Plan Code */
      plan_code: string;
    };
    /** AnalyzeIn */
    AnalyzeIn: {
      /** Url */
      url: string;
    };
    /** AnalyzeOut */
    AnalyzeOut: {
      /** Source */
      source: string;
      /** Homepage Url */
      homepage_url: string;
      /** Domain */
      domain: string;
      /** Platform */
      platform: string;
      /** Brand Name */
      brand_name: string;
      /** Detected Languages */
      detected_languages: string[];
      /** Industry */
      industry: string | null;
      /** City */
      city: string | null;
      /** Country */
      country: string;
      /** Competitors */
      competitors: string[];
    };
    /** BulkKeywordsIn */
    BulkKeywordsIn: {
      /** Items */
      items: components["schemas"]["KeywordIn"][];
    };
    /** BulkPromptsIn */
    BulkPromptsIn: {
      /** Items */
      items: components["schemas"]["PromptIn"][];
    };
    /** BulkResult */
    BulkResult: {
      /** Created */
      created: number;
      /** Skipped Duplicates */
      skipped_duplicates: number;
    };
    /** CompleteIn */
    CompleteIn: {
      site: components["schemas"]["SiteCreateIn"];
      /** Keywords */
      keywords?: components["schemas"]["KeywordIn"][];
      /** Prompts */
      prompts?: components["schemas"]["PromptIn"][];
    };
    /** EmailIn */
    EmailIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InvitationIn */
    InvitationIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Role
       * @default member
       * @enum {string}
       */
      role: "admin" | "member" | "viewer";
    };
    /** InvitationOut */
    InvitationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Role */
      role: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Accepted At */
      accepted_at: string | null;
    };
    /** KeywordIn */
    KeywordIn: {
      /** Keyword */
      keyword: string;
      /** Language */
      language: string;
      /** Country */
      country?: string | null;
      /** City */
      city?: string | null;
      /**
       * Device
       * @default desktop
       * @enum {string}
       */
      device: "desktop" | "mobile";
      /** Tags */
      tags?: string[];
    };
    /** KeywordOut */
    KeywordOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      /** Keyword */
      keyword: string;
      /** Language */
      language: string;
      /** Country */
      country: string;
      /** City */
      city: string | null;
      /** Device */
      device: string;
      /** Tags */
      tags: string[];
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** LoginIn */
    LoginIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** MeUpdateIn */
    MeUpdateIn: {
      /** Full Name */
      full_name?: string | null;
      /** Ui Language */
      ui_language?: ("en" | "ar") | null;
    };
    /** MemberOut */
    MemberOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /** Role */
      role: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** MemberUpdateIn */
    MemberUpdateIn: {
      /**
       * Role
       * @enum {string}
       */
      role: "owner" | "admin" | "member" | "viewer";
    };
    /** Ok */
    Ok: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /** OrgCreateIn */
    OrgCreateIn: {
      /** Name */
      name: string;
    };
    /** OrgOut */
    OrgOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Role */
      role: string;
      plan: components["schemas"]["PlanOut"];
      /** Addons */
      addons: {
        [key: string]: unknown;
      };
      usage: components["schemas"]["UsageOut"];
    };
    /** OrgSummary */
    OrgSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Role */
      role: string;
      /** Plan Code */
      plan_code: string;
    };
    /** OrgUpdateIn */
    OrgUpdateIn: {
      /** Name */
      name: string;
    };
    /** PasswordResetIn */
    PasswordResetIn: {
      /** Token */
      token: string;
      /** Password */
      password: string;
    };
    /** PlanOut */
    PlanOut: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Sort Order */
      sort_order: number;
      /** Is Public */
      is_public: boolean;
      /** Max Sites */
      max_sites: number;
      /** Max Keywords */
      max_keywords: number;
      /** Max Prompts */
      max_prompts: number;
      /** Max Engines */
      max_engines: number;
      /** Allowed Engines */
      allowed_engines: string[];
      /** Max Languages Per Site */
      max_languages_per_site: number;
      /** Addon Languages */
      addon_languages: string[];
      /** Check Frequency */
      check_frequency: string;
      /** Audits Per Month */
      audits_per_month: number;
      /** Trial Days */
      trial_days: number | null;
    };
    /**
     * Platform
     * @enum {string}
     */
    Platform:
      | "wordpress"
      | "shopify"
      | "wix"
      | "webflow"
      | "squarespace"
      | "framer"
      | "salla"
      | "zid"
      | "nextjs"
      | "nuxt"
      | "react_spa"
      | "vue_spa"
      | "astro"
      | "static"
      | "custom_backend"
      | "unknown";
    /** PromptIn */
    PromptIn: {
      /** Prompt Text */
      prompt_text: string;
      /** Language */
      language: string;
      /** Country */
      country?: string | null;
      /** @default informational */
      intent: components["schemas"]["PromptIntent"];
      /** Tags */
      tags?: string[];
    };
    /**
     * PromptIntent
     * @enum {string}
     */
    PromptIntent: "informational" | "commercial" | "local" | "comparison" | "navigational";
    /** PromptOut */
    PromptOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Site Id
       * Format: uuid
       */
      site_id: string;
      /** Prompt Text */
      prompt_text: string;
      /** Language */
      language: string;
      /** Country */
      country: string;
      /** Intent */
      intent: string;
      /** Tags */
      tags: string[];
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * Rendering
     * @enum {string}
     */
    Rendering: "server" | "client" | "hybrid" | "unknown";
    /** SessionOut */
    SessionOut: {
      user: components["schemas"]["UserOut"];
      /** Orgs */
      orgs: components["schemas"]["OrgSummary"][];
      /** Csrf Token */
      csrf_token: string;
    };
    /** SignupIn */
    SignupIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Full Name */
      full_name: string;
      /** Org Name */
      org_name?: string | null;
      /**
       * Ui Language
       * @default en
       * @enum {string}
       */
      ui_language: "en" | "ar";
    };
    /** SiteCreateIn */
    SiteCreateIn: {
      /** Name */
      name: string;
      /** @default unknown */
      platform: components["schemas"]["Platform"];
      /**
       * Platform Confirmed
       * @default false
       */
      platform_confirmed: boolean;
      /**
       * Primary Language
       * @default en
       */
      primary_language: string;
      /** Additional Languages */
      additional_languages?: string[];
      /**
       * Default Country
       * @default US
       */
      default_country: string;
      /** Default City */
      default_city?: string | null;
      /** Industry */
      industry?: string | null;
      /** Brand Names */
      brand_names?: {
        [key: string]: string[];
      };
      /** Competitor Domains */
      competitor_domains?: string[];
      /** Homepage Url */
      homepage_url: string;
    };
    /** SiteOut */
    SiteOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Domain */
      domain: string;
      /** Homepage Url */
      homepage_url: string;
      /** Platform */
      platform: string;
      /** Platform Confirmed */
      platform_confirmed: boolean;
      /** Rendering */
      rendering: components["schemas"]["Rendering"] | string;
      /** Primary Language */
      primary_language: string;
      /** Additional Languages */
      additional_languages: string[];
      /** Default Country */
      default_country: string;
      /** Default City */
      default_city: string | null;
      /** Industry */
      industry: string | null;
      /** Brand Names */
      brand_names: {
        [key: string]: string[];
      };
      /** Competitor Domains */
      competitor_domains: string[];
      /** Site Key */
      site_key: string;
      /** Verification Token */
      verification_token: string;
      /** Verification Method */
      verification_method: string | null;
      /** Verified At */
      verified_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** SiteUpdateIn */
    SiteUpdateIn: {
      /** Name */
      name?: string | null;
      platform?: components["schemas"]["Platform"] | null;
      /** Platform Confirmed */
      platform_confirmed?: boolean | null;
      /** Primary Language */
      primary_language?: string | null;
      /** Additional Languages */
      additional_languages?: string[] | null;
      /** Default Country */
      default_country?: string | null;
      /** Default City */
      default_city?: string | null;
      /** Industry */
      industry?: string | null;
      /** Brand Names */
      brand_names?: {
        [key: string]: string[];
      } | null;
      /** Competitor Domains */
      competitor_domains?: string[] | null;
    };
    /** StatusIn */
    StatusIn: {
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "paused";
    };
    /** SuggestIn */
    SuggestIn: {
      /** Brand Name */
      brand_name: string;
      /** Industry */
      industry: string;
      /** City */
      city?: string | null;
      /** Languages */
      languages: string[];
    };
    /** SuggestOut */
    SuggestOut: {
      /** Source */
      source: string;
      /** Keywords */
      keywords: components["schemas"]["SuggestedKeyword"][];
      /** Prompts */
      prompts: components["schemas"]["SuggestedPrompt"][];
    };
    /** SuggestedKeyword */
    SuggestedKeyword: {
      /** Keyword */
      keyword: string;
      /** Language */
      language: string;
    };
    /** SuggestedPrompt */
    SuggestedPrompt: {
      /** Prompt Text */
      prompt_text: string;
      /** Language */
      language: string;
      /** Intent */
      intent: string;
    };
    /** TokenIn */
    TokenIn: {
      /** Token */
      token: string;
    };
    /** UsageOut */
    UsageOut: {
      /** Sites */
      sites: number;
      /** Keywords */
      keywords: number;
      /** Prompts */
      prompts: number;
    };
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /** Ui Language */
      ui_language: string;
      /** Is Platform Admin */
      is_platform_admin: boolean;
      /** Email Verified */
      email_verified: boolean;
      /** Has Password */
      has_password: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  signup_auth_signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"];
        };
      };
    };
  };
  update_me_auth_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MeUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_verification_auth_verify_email_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
    };
  };
  verify_email_auth_verify_email_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_password_reset_auth_password_reset_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_password_auth_password_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  google_start_auth_google_start_get: {
    parameters: {
      query?: {
        next?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  google_callback_auth_google_callback_get: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_my_orgs_orgs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrgSummary"][];
        };
      };
    };
  };
  create_org_orgs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrgCreateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrgSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_current_org_org_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrgOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_current_org_org_patch: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrgUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_members_org_members_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_member_org_members__membership_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        membership_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_member_org_members__membership_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        membership_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_invitations_org_invitations_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_invitation_org_invitations_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_invitation_org_invitations__invitation_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  accept_invitation_invitations_accept_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sites_sites_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_site_sites_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SiteCreateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_site_sites__site_id__get: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_site_sites__site_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_site_sites__site_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SiteUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_keywords_sites__site_id__keywords_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_keywords_sites__site_id__keywords_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkKeywordsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_keyword_sites__site_id__keywords__keyword_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
        keyword_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_keyword_status_sites__site_id__keywords__keyword_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
        keyword_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StatusIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KeywordOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_prompts_sites__site_id__prompts_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_prompts_sites__site_id__prompts_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkPromptsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_prompt_sites__site_id__prompts__prompt_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Ok"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_prompt_status_sites__site_id__prompts__prompt_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path: {
        site_id: string;
        prompt_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StatusIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PromptOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  analyze_onboarding_analyze_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalyzeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalyzeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggestions_onboarding_suggestions_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SuggestIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuggestOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_onboarding_complete_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Org-Id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_public_plans_plans_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanOut"][];
        };
      };
    };
  };
  list_orgs_admin_orgs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminOrgOut"][];
        };
      };
    };
  };
  set_org_plan_admin_orgs__org_id__plan_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        org_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminSetPlanIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminOrgOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_org_admin_orgs__org_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        org_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminOrgUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminOrgOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_all_plans_admin_plans_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanOut"][];
        };
      };
    };
  };
  update_plan_admin_plans__plan_code__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminPlanUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
