// AUTO-GENERATED by scripts/brand_sync.py from config/brand.json. Do not edit.

export const BRAND = {
  "api_key_prefix": "ql",
  "brand_slug": "quardlink",
  "colors": {
    "primary": "#2563eb",
    "primary_foreground": "#ffffff"
  },
  "company_name": "QuardLink",
  "crawler_user_agent_token": "QuardLinkBot",
  "dns_txt_prefix": "quardlink-verification=",
  "email_from_name": "QuardLink",
  "npm_scope": "@quardlink",
  "product_name": "QuardLink",
  "sdk_package": "@quardlink/sdk",
  "site_key_prefix": "qls",
  "snippet_filename": "agent.js",
  "snippet_global": "QuardLink",
  "verification_meta_name": "quardlink-verification",
  "wp_plugin_slug": "quardlink"
} as const;

export type Brand = typeof BRAND;
